#!/usr/bin/env tsx
/**
 * Generate a cryptographically secure JWT secret for HS256.
 *
 * Usage:
 *   pnpm gen:secret           # Print to stdout
 *   pnpm gen:secret --write   # Append to .env.local (creates if missing)
 *
 * The generated secret is 64 random bytes encoded as base64url.
 * That's 512 bits of entropy — well above the 256-bit minimum for HS256.
 *
 * NEVER commit the secret. .env.local is in .gitignore.
 */

import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { resolve } from 'node:path';

function generateSecret(): string {
  return randomBytes(64).toString('base64url');
}

function writeToEnvLocal(secret: string): void {
  const envPath = resolve(process.cwd(), '.env.local');

  if (existsSync(envPath)) {
    const content = readFileSync(envPath, 'utf8');
    if (content.match(/^JWT_SECRET=/m)) {
      console.error('.env.local already has JWT_SECRET. Edit it manually or delete the line first.');
      process.exit(1);
    }
    appendFileSync(envPath, `\nJWT_SECRET="${secret}"\n`, 'utf8');
    console.log('Appended JWT_SECRET to .env.local');
  } else {
    writeFileSync(
      envPath,
      `# Generated by scripts/gen-jwt-secret.ts on ${new Date().toISOString()}\n` +
        `# DO NOT COMMIT .env.local\n\n` +
        `JWT_SECRET="${secret}"\n`,
      'utf8'
    );
    console.log('Created .env.local with JWT_SECRET');
  }
}

const shouldWrite = process.argv.includes('--write');
const secret = generateSecret();

if (shouldWrite) {
  writeToEnvLocal(secret);
} else {
  console.log('Generated JWT_SECRET (64 bytes, base64url):');
  console.log('');
  console.log(`  JWT_SECRET="${secret}"`);
  console.log('');
  console.log('Copy the line above into your .env.local, or run with --write to do it automatically.');
}